# Generated by Django 4.0.1 on 2022-05-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0002_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
